# Generated by Django 3.1 on 2020-09-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='photographer',
            new_name='user',
        ),
    ]
